name: Sync

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
   - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: 'backslashxx/KernelSU'
          ref: "${{ github.ref_name }}"
          submodules: 'recursive'
          fetch-depth: '0'
          token: "${{ secrets.WORKFLOW_TOKEN }}"

      - name: Apply changes
        run: |
          curl -LSs https://gist.github.com/malkist01/8b74b5f2c6b1da211ef93c3176d0e235/raw/xxksu.patch > xxksu.patch
          patch -p1 < xxksu.patch

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          find . -name "*.orig" -delete
          rm xxksu.patch

          git add .
          git commit -m "Apply changes"

      - name: Push
        env:
          GH_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
        run: |
          git remote add my https://github.com/${{ github.repository }}
          git push my ${{ github.ref_name }} -f

          gh workflow run "release.yml" -R "${{ github.repository }}" -r "${{ github.ref_name }}"
